services:
    postgres:
        image: postgres:latest
        ports:
            - '${DB_PORT}:${DB_PORT}'
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgres_data:/var/lib/postgresql/data
    pgadmin:
      image: dpage/pgadmin4
      ports:
          - "5050:80"
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
volumes:
    postgres_data:
